### ISSUE TITLE
Does DI-drive support multi-agent training?

### ISSUE THREAD

**Issue by Meta-YZ** [opendilab/DI-drive#11]
## ISSUE TEMPLATE

- [ ] I have marked all applicable categories:
    + [X] new feature request
- [X] I have visited the [readme](https://github.com/opendilab/DI-drive/blob/main/README.md) and [doc](https://opendilab.github.io/DI-drive/)
- [X] I have searched through the [issue tracker](https://github.com/opendilab/DI-drive/issues) and [pr tracker](https://github.com/opendilab/DI-drive/pulls)

Does DI-drive support multi-agent training? Like this [macad-gym](https://github.com/praveen-palanisamy/macad-gym/tree/master/src/macad_gym/carla), and it based CARLA also.

**Comment by RobinC94** [comment]
Hello, MARL is in our developing roadmap. If you have an urgent need in this regard, you can describe it to our mailbox or in slack group. We will consider increasing the priority as appropriate.

**Comment by Meta-YZ** [comment]
> Hello, MARL is in our developing roadmap. If you have an urgent need in this regard, you can describe it to our mailbox or in slack group. We will consider increasing the priority as appropriate.

Thank you for your replay. There are very few autonomous driving simulators for multi-agent rl, so I'm looking forfward to your work! 
CARLA could support parallel multi-agent training in multiple vectors envs. That is my wish.

**Comment by RobinC94** [comment]
> > Hello, MARL is in our developing roadmap. If you have an urgent need in this regard, you can describe it to our mailbox or in slack group. We will consider increasing the priority as appropriate.
> 
> Thank you for your replay. There are very few autonomous driving simulators for multi-agent rl, so I'm looking forfward to your work! CARLA could support parallel multi-agent training in multiple vector envs. That is my wish.

BTW，we would like to know which type of marl you are more likely to use, similar with MACAD which is a multi-vehicle cooperation in intersection, or common driving case with several cars like [highway-env](https://github.com/eleurent/highway-env)?

**Comment by Meta-YZ** [comment]
> > > Hello, MARL is in our developing roadmap. If you have an urgent need in this regard, you can describe it to our mailbox or in slack group. We will consider increasing the priority as appropriate.
> > 
> > 
> > Thank you for your replay. There are very few autonomous driving simulators for multi-agent rl, so I'm looking forfward to your work! CARLA could support parallel multi-agent training in multiple vector envs. That is my wish.
> 
> BTW，we would like to know which type of marl you are more likely to use, similar with MACAD which is a multi-vehicle cooperation in intersection, or common driving case with several cars like [highway-env](https://github.com/eleurent/highway-env)?

Oh, I'd like to Multi-vehicle cooperation  and competition in intersection or ramp merge. I think that usage of the more complex  scenarios is our need like MACAD, MetaDrive, and SMARTS......, not highway-env

**Comment by RobinC94** [comment]
> > > > Hello, MARL is in our developing roadmap. If you have an urgent need in this regard, you can describe it to our mailbox or in slack group. We will consider increasing the priority as appropriate.
> > > 
> > > 
> > > Thank you for your replay. There are very few autonomous driving simulators for multi-agent rl, so I'm looking forfward to your work! CARLA could support parallel multi-agent training in multiple vector envs. That is my wish.
> > 
> > 
> > BTW，we would like to know which type of marl you are more likely to use, similar with MACAD which is a multi-vehicle cooperation in intersection, or common driving case with several cars like [highway-env](https://github.com/eleurent/highway-env)?
> 
> Oh, I'd like to Multi-vehicle cooperation and competition in intersection or ramp merge. I think that usage of the more complex scenarios is our need like MACAD, MetaDrive, and SMARTS......, not highway-env

Get it. In fact we are trying to add MetaDrive support in DI-drive as well. You may see this feature in next version.

**Comment by dineshresearch** [comment]
@RobinC94 Hello I was going through 
https://github.com/opendilab/DI-drive/blob/gl-dev/core/envs/md_macro_env.py

will this currently support multi agent RL(MARL) algos like https://github.com/decisionforce/CoPO

I am particularly interested in the Multi-vehicle cooperation and competition at intersection case?

any help would be highly appreciated

**Comment by RobinC94** [comment]
> 

Hello, thanks for your suggestion. We will go through the aforementioned method and code and make a plan for MetaDrive MARL environment soon.
