### ISSUE TITLE
BeV Speed RL Pretrain Model

### ISSUE THREAD

**Issue by yihhhh** [opendilab/DI-drive#13]
## ISSUE TEMPLATE
Hi DI-Drive team, 
I appreciate your work and am trying to use this platform. Could you provide any access to your pretrained models of the BEV Speed RL? Thank you very much.

- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [x] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-drive/blob/main/README.md) and [doc](https://opendilab.github.io/DI-drive/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-drive/issues) and [pr tracker](https://github.com/opendilab/DI-drive/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import core, torch, sys
  print(core.__version__, torch.__version__, sys.version, sys.platform)
  ```

**Comment by RobinC94** [comment]
Hi, we have provided a DQN pretrain model of BEV speed RL training in the following link.
[Plus25.pth](http://opendilab.org/download/DI-drive/simple_rl/Plus25.pth )
We will soon update pretrains into documents.
thx
