### ISSUE TITLE
CICT Training failed using the default setting

### ISSUE THREAD

**Issue by yihhhh** [opendilab/DI-drive#15]
## ISSUE TEMPLATE

- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [x] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-drive/blob/main/README.md) and [doc](https://opendilab.github.io/DI-drive/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-drive/issues) and [pr tracker](https://github.com/opendilab/DI-drive/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import core, torch, sys
  print(core.__version__, torch.__version__, sys.version, sys.platform)
  ```
Hi, I'm using the DI-drive repo to train the CICT model of my own. I collected data and trained the GAN model using the default parameter settings, it turns out that the discriminator loss is always 0, which leads to the generator stop learning anything after several iterations. I'm wondering if the provided pretrained model is trained using the default setting? If not, can you provide some reference for the parameter settings? Thanks very much.

**Comment by RobinC94** [comment]
Hi, sorry for the delay, we are trying to fix it.

**Comment by RobinC94** [comment]
Hi, sorry for delay. Could you please provide the DI-drive and CARLA server version you used? It will be better if the training entry file is also provided, thanks!
