### ISSUE TITLE
Automatically core dumped at server

### ISSUE THREAD

**Issue by MyIDis12138** [opendilab/DI-drive#20]
when I finished installation of DI-drive and run auto_run.py, the server core dumped in few seconds.
I have also try other python files and they all caused this problem. I had also tried the examples provide in Carla/PythonAPI/examples, the problem didn't rise. 

I used the latest DI-drive and DI-Engine 3.1
Python version: 3.7
torch version: 1.8.0
Ubuntu 22.04

```
Traceback (most recent call last):
  File "/home/yang/DI-drive/demo/auto_run/auto_run.py", line 80, in <module>
    main(main_config)
  File "/home/yang/DI-drive/demo/auto_run/auto_run.py", line 75, in main
    evaluator.eval(cfg.policy.eval.evaluator.reset_param)
  File "/home/yang/DI-drive/core/eval/single_carla_evaluator.py", line 74, in eval
    obs = self._env.reset(**reset_param)
  File "/home/yang/DI-drive/core/envs/drive_env_wrapper.py", line 57, in reset
    obs = {'birdview': birdview, 'vehicle_state': obs['vehicle_state']}
KeyError: 'vehicle_state'
WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 2623 (sensor.other.collision) 
terminate called without an active exception
Aborted (core dumped)
```

**Comment by RobinC94** [comment]
Hi, this is caused by a mixture of usage between CARLA and MetaDrive simulator and we are fixing it right away.

**Comment by MyIDis12138** [comment]
> > when I finished installation of DI-drive and run auto_run.py, the server core dumped in few seconds. I have also try other python files and they all caused this problem. I had also tried the examples provide in Carla/PythonAPI/examples, the problem didn't rise.
> > I used the latest DI-drive and DI-Engine 3.1 Python version: 3.7 torch version: 1.8.0 Ubuntu 22.04
> > ```
> > Traceback (most recent call last):
> >   File "/home/yang/DI-drive/demo/auto_run/auto_run.py", line 80, in <module>
> >     main(main_config)
> >   File "/home/yang/DI-drive/demo/auto_run/auto_run.py", line 75, in main
> >     evaluator.eval(cfg.policy.eval.evaluator.reset_param)
> >   File "/home/yang/DI-drive/core/eval/single_carla_evaluator.py", line 74, in eval
> >     obs = self._env.reset(**reset_param)
> >   File "/home/yang/DI-drive/core/envs/drive_env_wrapper.py", line 57, in reset
> >     obs = {'birdview': birdview, 'vehicle_state': obs['vehicle_state']}
> > KeyError: 'vehicle_state'
> > WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 2623 (sensor.other.collision) 
> > terminate called without an active exception
> > Aborted (core dumped)
> > ```
> 
> Hi, we will fix this bug this weekend. It is recommended to use the DI-drive version 0.3.3 first!

Great! I will try DI-drive 0.3.3 for my work, Thank you very much!

**Comment by zijinoier** [comment]
> > when I finished installation of DI-drive and run auto_run.py, the server core dumped in few seconds. I have also try other python files and they all caused this problem. I had also tried the examples provide in Carla/PythonAPI/examples, the problem didn't rise.
> > I used the latest DI-drive and DI-Engine 3.1 Python version: 3.7 torch version: 1.8.0 Ubuntu 22.04
> > ```
> > Traceback (most recent call last):
> >   File "/home/yang/DI-drive/demo/auto_run/auto_run.py", line 80, in <module>
> >     main(main_config)
> >   File "/home/yang/DI-drive/demo/auto_run/auto_run.py", line 75, in main
> >     evaluator.eval(cfg.policy.eval.evaluator.reset_param)
> >   File "/home/yang/DI-drive/core/eval/single_carla_evaluator.py", line 74, in eval
> >     obs = self._env.reset(**reset_param)
> >   File "/home/yang/DI-drive/core/envs/drive_env_wrapper.py", line 57, in reset
> >     obs = {'birdview': birdview, 'vehicle_state': obs['vehicle_state']}
> > KeyError: 'vehicle_state'
> > WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 2623 (sensor.other.collision) 
> > terminate called without an active exception
> > Aborted (core dumped)
> > ```
> 
> Hi, we will fix this bug this weekend. It is recommended to use the DI-drive version 0.3.3 first!

hello @RobinC94 , I tried the latest DI-Drive 0.3.4 and the recommend version 0.3.3,but the automatically core dumped problem still appear.
I use Python 3.7.0 and Ubuntu 20.04.
Carla and MetaDrive are both installed.
```bash
Traceback (most recent call last):
  File "auto_run.py", line 78, in <module>
    main(main_config)
  File "auto_run.py", line 73, in main
    evaluator.eval(cfg.policy.eval.evaluator.reset_param)
  File "/home/wayne/code/DI-drive/core/eval/single_carla_evaluator.py", line 74, in eval
    obs = self._env.reset(**reset_param)
  File "/home/wayne/code/DI-drive/core/envs/drive_env_wrapper.py", line 57, in reset
    obs = {'birdview': birdview, 'vehicle_state': obs['vehicle_state']}
KeyError: 'vehicle_state'

```

**Comment by RobinC94** [comment]
> > > when I finished installation of DI-drive and run auto_run.py, the server core dumped in few seconds. I have also try other python files and they all caused this problem. I had also tried the examples provide in Carla/PythonAPI/examples, the problem didn't rise.
> > > I used the latest DI-drive and DI-Engine 3.1 Python version: 3.7 torch version: 1.8.0 Ubuntu 22.04
> > > ```
> > > Traceback (most recent call last):
> > >   File "/home/yang/DI-drive/demo/auto_run/auto_run.py", line 80, in <module>
> > >     main(main_config)
> > >   File "/home/yang/DI-drive/demo/auto_run/auto_run.py", line 75, in main
> > >     evaluator.eval(cfg.policy.eval.evaluator.reset_param)
> > >   File "/home/yang/DI-drive/core/eval/single_carla_evaluator.py", line 74, in eval
> > >     obs = self._env.reset(**reset_param)
> > >   File "/home/yang/DI-drive/core/envs/drive_env_wrapper.py", line 57, in reset
> > >     obs = {'birdview': birdview, 'vehicle_state': obs['vehicle_state']}
> > > KeyError: 'vehicle_state'
> > > WARNING: sensor object went out of the scope but the sensor is still alive in the simulation: Actor 2623 (sensor.other.collision) 
> > > terminate called without an active exception
> > > Aborted (core dumped)
> > > ```
> > 
> > 
> > Hi, we will fix this bug this weekend. It is recommended to use the DI-drive version 0.3.3 first!
> 
> hello @RobinC94 , I tried the latest DI-Drive 0.3.4 and the recommend version 0.3.3,but the automatically core dumped problem still appear. I use Python 3.7.0 and Ubuntu 20.04. Carla and MetaDrive are both installed.
> 
> ```shell
> Traceback (most recent call last):
>   File "auto_run.py", line 78, in <module>
>     main(main_config)
>   File "auto_run.py", line 73, in main
>     evaluator.eval(cfg.policy.eval.evaluator.reset_param)
>   File "/home/wayne/code/DI-drive/core/eval/single_carla_evaluator.py", line 74, in eval
>     obs = self._env.reset(**reset_param)
>   File "/home/wayne/code/DI-drive/core/envs/drive_env_wrapper.py", line 57, in reset
>     obs = {'birdview': birdview, 'vehicle_state': obs['vehicle_state']}
> KeyError: 'vehicle_state'
> ```

Sorry, I didn't see this for the issue is closed.
Maybe you can try the latest main branch, the bug in DriveEnvWrapper is fixed.
