### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Mming11** [opendilab/DI-drive#27]
![2023-04-09 16-15-56 的屏幕截图](https://user-images.githubusercontent.com/80202433/230762022-81c6c9d5-af99-4718-923a-e46ed392ec56.png)
运行metadrive下的这个py文件遇到这个error

**Comment by PaParaZz1** [comment]
这个问题可能是 DI-drive 与最新版本的 DI-engine 环境接口直接的适配关系，你可以尝试安装 0.4.2 版本的 DI-engine 来使用，应该是适配的。
