### ISSUE TITLE
Unstable AutoMPCPolicy

### ISSUE THREAD

**Issue by hz3014** [opendilab/DI-drive#28]
## ISSUE TEMPLATE

- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] system worker bug
    + [ ] system utils bug
    + [ ] code design/refactor
    + [ ] documentation request
    + [ ] new feature request
- [x] I have visited the [readme](https://github.com/opendilab/DI-drive/blob/main/README.md) and [doc](https://opendilab.github.io/DI-drive/)
- [x] I have searched through the [issue tracker](https://github.com/opendilab/DI-drive/issues) and [pr tracker](https://github.com/opendilab/DI-drive/pulls)
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import core, torch, sys
  print(core.__version__, torch.__version__, sys.version, sys.platform)
  ```

0.3.4 1.12.1+cu102 3.8.16 (default, Mar  2 2023, 03:21:46) 
[GCC 11.2.0] linux

I was trying the AutoMPCPolicy with script python auto_run.py
I noticed the agent is super unstable compared to AutoPIDPolicy. MPC agent hit the wall easily. I was wondering did you have this issue?

**Comment by timothijoe** [comment]
We use Model Predictive Control (MPC) to obtain the desired acceleration and front wheel steer. However, the Carla environment does not provide enough information for us to derive the corresponding function for throttle-to-acceleration mapping.
