### ISSUE TITLE
hi, i have another error, run simple_rl_train.py

### ISSUE THREAD

**Issue by hankerbit** [opendilab/DI-drive#30]
before i run it,  i config          
        collector_env_num=2,
        evaluator_env_num=1,
       dict(carla_host='localhost', carla_ports=[9000, 9006, 2]),
and start three carla servers with port-num 9000 9002 9004

then I get following error:

assert self._closed, "please first close the env manager" 

how can i fix it?
thx

**Comment by zqiilmc** [comment]
Have you solved the problem？

**Comment by zqiilmc** [comment]
> before i run it, i config collector_env_num=2, evaluator_env_num=1, dict(carla_host='localhost', carla_ports=[9000, 9006, 2]), and start three carla servers with port-num 9000 9002 9004
> 
> then I get following error:
> 
> assert self._closed, "please first close the env manager"
> 
> how can i fix it? thx

Have you solved the problem？

**Comment by leishi23** [comment]
same problem *"please first close the env manager"*
```
collector_env_num=1,
evaluator_env_num=1,
dict(carla_host='localhost', carla_ports=[9000, 90010, 4]),
```
and start three carla servers with port-num 9000 9004

**Comment by PaParaZz1** [comment]
You can try to move older version of DI-engine, like 0.4.0
