### ISSUE TITLE
ModuleNotFoundError: No module named 'ding'

### ISSUE THREAD

**Issue by weijielyu** [opendilab/DI-drive#5]
In the documentation for _End-to-End Model-Free Reinforcement Learning for Urban Driving using Implicit Affordances_, when I try to run `python collect_data.py`, there's an error in the import section:
`from ding.utils import EasyTimer`
`ModuleNotFoundError: No module named 'ding'`
Is that because the ding dir wasn't added into the Github repository? Could you help with that? Thanks!

**Comment by RobinC94** [comment]
Hi, have you successfully installed DI-engine?
You can try
`
pip install DI-engine
python -c 'import ding'
`

**Comment by weijielyu** [comment]
Hi, I installed DI-engine, now it can find module ding, but it gives me another error:
`File "/home/xxxxxxxx/.local/lib/python3.7/site-packages/core/data/dataset_saver.py", line 8, in <module>
    from core.utils.data_utils.data_writter import write_json, write_episode_lmdb
ModuleNotFoundError: No module named 'core.utils'`

**Comment by RobinC94** [comment]
Hi, are you still trying to run `python collect_data.py` in _Implicit Affordance_? I have tried in newest code of the _main_ branch and no error arose.

**Comment by weijielyu** [comment]
Oh, I reinstalled DI-drive and it works this time. Thank you!
